### ISSUE TITLE
Defuse kicks with bunnies

### ISSUE THREAD

**Issue by davidism** [sopython/rabbit#11]
Post a random cute picture after every kick to defuse the tension.

**Comment by kms70847** [comment]
Currently working on this. So far the only cute picture I have is:

http://i.imgur.com/6LqxbcH.jpg

Please post additional cute pictures here so I can incorporate them into the rotation.

**Comment by ztane** [comment]
Google imgur bunny:
- http://i.imgur.com/kw9y8.jpg
- http://i.imgur.com/670Cq.jpg
- http://i.imgur.com/NbGiSmd.jpg
- http://i.imgur.com/2ZYlX.jpg

**Comment by kms70847** [comment]
Excellent images. I have added them to the rotation.

This feature is now functionally complete, but if additional images are posted in here, I will add them.
